name: Docker Image CI
on: [push]
jobs:
  build:
    name: Capistrano ${{ matrix.version_list }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version_list: ["3.14"]
    steps:
    - uses: actions/checkout@v1
    - run: ./scripts/build.sh --push
      env:
        VERSION_LIST: ${{ matrix.version_list }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
